# Generated by Django 5.0.3 on 2024-03-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("remarks", models.TextField(blank=True)),
                ("timings", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("sent_profile", "Sent Profile"),
                            ("cmi", "CMI"),
                            ("pending", "Pending "),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leads.leads"
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tutors.tutors"
                    ),
                ),
            ],
        ),
    ]
