# Generated by Django 5.0.3 on 2024-03-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="preferred_rate",
            field=models.TextField(max_length=50),
        ),
    ]
