# Generated by Django 5.0.3 on 2024-03-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_alter_application_preferred_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="preferred_rate",
            field=models.CharField(max_length=50),
        ),
    ]
