# Generated by Django 5.0 on 2024-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("client_name", models.CharField(max_length=200)),
                ("client_number", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new_case", "New Case"),
                            ("tutors_sent", "Tutors Sent"),
                            ("tutors_needed", "Tutors Needed"),
                            ("closed", "Closed"),
                            ("activate_tuition_centres", "Activate Tuition Centres"),
                            ("premium_education", "Premium Education"),
                            ("issue_cases", "Issue Cases"),
                            ("follow_up_to_close", "Follow Up to Close"),
                            ("group_chats_created", "Group Chats Created"),
                            ("awaiting_confirmation", "Awaiting Confirmation"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="new_case",
                        max_length=50,
                    ),
                ),
                ("new_applications", models.IntegerField(default=0)),
                ("sent_applications", models.IntegerField(default=0)),
                ("pending_applications", models.IntegerField(default=0)),
                ("remarks", models.CharField(max_length=500)),
                ("many_tutor_link", models.CharField(max_length=500)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_reviewed_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
