# Generated by Django 5.0 on 2024-03-22 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leads",
            name="description",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leads",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="leads",
            name="many_tutor_link",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="leads",
            name="remarks",
            field=models.CharField(max_length=500),
        ),
    ]
