# Generated by Django 5.0.3 on 2024-03-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorinformation",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor_information",
                to="tutors.tutors",
            ),
        ),
    ]
