# Generated by Django 5.0 on 2024-03-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_leads_description_alter_leads_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="description",
            field=models.TextField(),
        ),
    ]
