# Generated by Django 5.0.3 on 2024-03-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_alter_tutorinformation_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
