# Generated by Django 5.0.3 on 2024-03-28 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_alter_leads_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorinformation",
            old_name="status",
            new_name="apply_status",
        ),
    ]
