# Generated by Django 5.0.3 on 2024-03-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutors",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tutors",
            name="phone_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
