# Generated by Django 5.0 on 2024-03-22 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0001_initial"),
    ]

    operations = []
