# Generated by Django 5.0 on 2024-03-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tutors", "0002_auto_20240322_1259"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("postal_code", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("remarks", models.TextField()),
                ("bio", models.TextField()),
                ("current_occupation", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("additional_information", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="tutors.tutors",
                    ),
                ),
            ],
        ),
    ]
