# Generated by Django 5.0 on 2024-03-22 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0004_auto_20240322_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutors",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
